gettext/edit{,-js}-po: Serveral enhancements.

diff --git a/scripts/gettext/edit-js-po b/scripts/gettext/edit-js-po
--- a/scripts/gettext/edit-js-po
+++ b/scripts/gettext/edit-js-po
@@ -1,16 +1,19 @@
 #!/bin/sh
 
-if [ -z "$1" ]
+PKG="$1"
+NAME="$(echo "$PKG" | sed 's/^stsbl-iserv-//')"
+
+if [ -z "$PKG" ] || [ -z "$NAME" ]
 then
-  echo "Package is missing!" &>2
+  echo "Usage: $0 <package>" 1>&2
   exit 1
 fi
 
-if [ -f "/var/lib/translations/po/iserv3/de/$1""-js.po" ]
+if [ -f "/var/lib/translations/po/iserv3/de/$NAME""-js.po" ]
 then
-  stsbl-dev-gettext "stsbl-iserv-$1"
-  vim -p "/var/lib/translations/po/iserv3/de/$1""-js.po"
-  stsbl-dev-gettext "stsbl-iserv-$1"
+  stsbl-dev-gettext "$PKG"
+  vim -p "/var/lib/translations/po/iserv3/de/$NAME""-js.po"
+  stsbl-dev-gettext "$PKG"
 else
-  echo "Invalid package name!" &>2
+  echo "Invalid package name!" 1>&2
 fi
